language: node_js
node_js:
  - "14.8"
  - "12.18"
before_install:
  - if [[ `npm -v` < 5* ]]; then npm i -g npm@5; fi
install:
  - npm install
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

