language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs-2"
  - "iojs-3"
  - "4"
install:
  - npm install
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8


